print('Choose a circuit')
print('1. R-L circuit','\n2.R-C circuit','\n3.R-L-C Circuit')
n=int(input('Enter a number:'))
#try:
import math
#except ValueError: 
#        print('Input not defined')
if n==1:
        print('The chosen circuit is a R-L circuit')
        print('1.Series ')
        try:
                p=int(input('Enter your choice'))
        except Exception:
                print('Input not defined')
        if p==1:
                print('The selected circuit is a series R-L Circuit')
        #R-L Circuit
                a=input('Enter the given quantities, Z,XL,R').split()
                s1={'Z','XL','R'}
                b=set(a)
                if s1-b==set('Z'):
                  print('The quantity to be calculated is Impendence')
                  print('The required formula is  z*z=r*r+XL*XL')
                  R=int(input('Enter the value of resistance:'))
                  XL=int(input('Enter the value of inductive reactance:'))
                  r=math.sqrt(R*R+XL*XL)
                  print('The impedence is:',r)
                if s1-b==set('XL'):
                  print('The quantity to be calculated is Inductive reactance')
                  print('The required formula is XL*XL=z*z-r*r')
                  Z=int(input('Enter the value of impedence:'))
                  R=int(input('Enter the value of resistance:'))      
                  print('The inductive reactance is:',(Z*Z-R*R)**0.5)
                if s1-b==set('R'):
                  print('The quantity to be calculated is resistance')
                  print('The required formula is r*r=z*z-XL*XL')
                  Z=int(input('Enter the value of impedence:'))
                  XL=int(input('Enter the value of inductive reactace:'))
                  print('The resistance is:', (Z*Z-XL*XL)**0.5)
                import turtle
                t=turtle
                t.color('red')
                t.forward(100)
                t.left(45)
                t.forward(10)
                t.right(90)
                t.forward(10)
#RL
                t.left(90)
                t.forward(10)
                t.right(90)
                t.forward(10)
                t.left(90)
                t.forward(10)
                t.right(90)
                t.forward(10)
                t.left(90)
                t.forward(10)
                t.right(90)
                t.forward(10)
                t.left(45)
                t.forward(100)
                t.right(90)
                t.penup()
                t.forward(25)
                t.left(90)
                t.forward(25)
                t.pendown()
                for i in range(4):
                    t.circle(25)
                    t.penup()
                    t.forward(10)
                    t.pendown()
                t.left(90)
                t.penup()
                t.forward(25)
                t.right(90)
                t.forward(14)
                t.pendown()
                t.forward(25)
                t.forward(30)
                t.right(90)
                t.forward(50)
                t.left(90)
                t.forward(50)
                t.right(90)
                t.forward(5)
                t.right(180)
                t.forward(10)
                t.right(180)
                t.forward(5)
                t.left(90)
                t.penup()
                t.forward(5)
                t.pendown()
                t.left(90)
                t.forward(10)
                t.right(180)
                t.forward(20)
                t.right(180)
                t.forward(10)
                t.right(90)
                t.forward(20)
                t.right(90)
                t.forward(20)
                t.right(90)
                t.forward(480)
                t.right(90)
                t.forward(70)
                t.goto(0,0)

              
                
if n==2:
        print('The chosen circuit is a R-C circuit')
        print('1.Series ')
        o=int(input('Enter your choice'))
        #R-C Circuit
        if o==1:
                print('The given circuit is series R-C Circuit')
                c=input('Enter the given quantities, Z,XC,R').split()
                s2={'Z','XC','R'}    
                d=set(c)  
                if s2-d==set('Z'):
                  print('The quantity to be calculated is impedence')
                  print('The required formula is z*z=r*r+XC*XC')
                  R=int(input('Enter the value of resistance:'))
                  XC=int(input('Enter the value of capacitive reactance:'))
                  print('The impedence is:',(R*R+XC*XC)**0.5)
                if s2-d==set('XC'):
                  print('The quantity to be calculated is Capacitive reactance')
                  print('The required formula is XC*XC=z*z-r*r')
                  Z=int(input('Enter the value of impedence:'))
                  R=int(input('Enter the value of resistance:'))      
                  print('The Capacitive reactance is:',(Z*Z-R*R)**0.5)
                if s2-d==set('R'):
                  print('The quantity to be calculated is resistance')
                  print('The required formula is r*r=z*z-XC*XC')
                  Z=int(input('Enter the value of impedence:'))
                  XC=int(input('Enter the value of Capacitive reactace:'))
                  print('The resistance is:', (Z*Z-XC*XC)**0.5)
                import turtle
                t=turtle
                t.color('red')
                t.forward(100)
                t.left(45)
                t.forward(10)
                t.right(90)
                t.forward(10)
                t.left(90)
                t.forward(10)
                t.right(90)
                t.forward(10)
                t.left(90)
                t.forward(10)
                t.right(90)
                t.forward(10)
                t.left(90)
                t.forward(10)
                t.right(90)
                t.forward(10)
                t.left(45)
                t.forward(100)
                t.right(90)
                t.forward(10)
                t.right(180)
                t.forward(20)
                t.right(180)
                t.forward(10)
                t.left(90)
                t.penup()
                t.forward(5)
                t.pendown()
                t.right(90)
                t.forward(10)
                t.right(180)
                t.forward(20)
                t.right(180)
                t.forward(10)
                t.left(90)
                t.forward(100)
                t.circle(50)
                t.penup()
                t.left(90)
                t.forward(10)
                t.right(90)
                t.pendown()
                t.left(120)
                t.forward(60)
                t.right(180)
                t.forward(60)
                t.left(120)
                t.forward(60)
                t.right(180)
                t.forward(60)
                t.left(45)
                t.penup()
                t.forward(10)
                t.pendown()
                t.right(15)
                t.right(90)
                t.right(180)
                t.forward(50)
                t.right(90)
                t.forward(50)
                t.right(90)
                t.forward(500)
                t.right(90)
                t.forward(50)
                t.goto(0,0)
                t.hideturtle()
        
if  n==3:
         print('The chosen circuit is a R-L-C circuit')
         #R-L-C Circuit
         e=input('Enter the given quantites Z,XC,XL,R').split()
         s3={'Z','XC','R','XL'}
         f=set(e)
         if s3-f==set('Z'):
            print('The quantity to be calculated is impedence')
            print('The required formula is z*z=r*r+XC*XC+XL*XL')
            R=int(input('Enter the value of resistance:'))
            XC=int(input('Enter the value of capacitive reactance:'))
            XL=int(input('Enter the value of Inductive reactance'))
            print('The impedence is:',(R*R+XC*XC+XL*XL)**0.5)
         if s3-f==set('XC'):
            print('The quantity to be calculated is Capacitive reactance')
            print('The required formula is XC*XC=z*z-r*r-XL*XL')
            Z=int(input('Enter the value of impedence:'))
            XL=int(input('Enter the value of Inductive reactance:'))
            R=int(input('Enter the value of resistance:'))      
            print('The Capacitive reactance is:',(Z*Z-R*R-XL*XL)**0.5)
         if s3-f==set('R'):
            print('The quantity to be calculated is resistance')
            print('The required formula is r*r=z*z-XC*XC-XL*XL')
            Z=int(input('Enter the value of impedence:'))
            XC=int(input('Enter the value of Capacitive reactace:'))
            XL=int(input('Enter the value of Inductive reactaance:'))
            print('The resistance is:', (Z*Z-XC*XC-XL*XL)**0.5)
         if s3-f==set('XL'):
            print('The quantity to be calculated is Inductive reactance')
            print('The required formula is XL*XL=z*z-r*r')
            Z=int(input('Enter the value of impedence:'))
            R=int(input('Enter the value of resistance:'))
            XC=int(input('Enter the value of capacitive reactance'))
            print('The inductive reactance is:',(Z*Z-R*R-XC*XC)**0.5)
         import turtle
         t=turtle
         t.color('red')
         t.hideturtle()
         t.forward(100)
         t.left(45)
         t.forward(10)
         t.right(90)
         t.forward(10)
         t.left(90)
         t.forward(10)
         t.right(90)
         t.forward(10)
         t.left(90)
         t.forward(10)
         t.right(90)
         t.forward(10)
         t.left(90)
         t.forward(10)
         t.right(90)
         t.forward(10)
         t.left(45)
         t.forward(100)
         t.right(90)
         t.penup()
         t.forward(25)
         t.left(90)
         t.forward(25)
         t.pendown()

         for i in range(4):
              t.circle(25)
              t.penup()
              t.forward(10)
              t.pendown()
         t.left(90)
         t.penup()
         t.forward(25)
         t.right(90)
         t.forward(14)
         t.pendown()
         t.forward(25)
         t.forward(30)
         t.left(90)
         t.forward(10)
         t.right(180)
         t.forward(20)
         t.right(180)
         t.forward(10)
         t.right(90)
         t.penup()
         t.forward(5)
         t.pendown()
         t.left(90)
         t.forward(10)
         t.right(180)
         t.forward(20)
         t.right(180)
         t.forward(10)
         t.right(90)
         t.forward(50)

         t.right(90)
         t.forward(50)
         t.left(90)
         t.forward(50)
         t.right(90)
         t.forward(5)
         t.right(180)
         t.forward(10)
         t.right(180)
         t.forward(5)
         t.left(90)
         t.penup()
         t.forward(5)
         t.pendown()
         t.left(90)
         t.forward(10)
         t.right(180)
         t.forward(20)
         t.right(180)
         t.forward(10)
         t.right(90)
         t.forward(20)
         t.right(90)
         t.forward(20)
         t.right(90)
         t.forward(580)
         t.right(90)
         t.forward(70)
         t.goto(0,0)
'''if n==4:
        print('The chosen circuit is a simple D.C. circuit')
        #D.C. Circuit
        #try:
        g=input('Enter the given quantities').split()
        #except Exception:
          #      print('Input not defined')
      #  else:
      #         print('Please enter the quantities in upper case letters')
        s4={'V','I','R'}    
        h=set(g)  
        if s4-h==set('V'):
          print('The quantity to be calculated is Voltage')
          print('The required formula isV=I*R')
          I=int(input('Enter the value of current'))
          R=int(input('Enter the value of resistance:'))
          print('The voltage is:',I*R)
        if s4-h==set('I'):
          print('The quantity to be calculated is Current')
          print('The required formula is V/R')
          V=int(input('Enter the value of voltage:'))
          R=int(input('Enter the value of resistance:'))      
          print('The Current is:',V/R)
        if s4-h==set('R'):
          print('The quantity to be calculated is resistance')
          print('The required formula is V/I')
          V=int(input('Enter the value of voltage:'))
          I=int(input('Enter the value of current'))
          print('The resistance is:', V/I)
if n>4 or n<1:
        print('Input not defined')
 #The exception is caught by the python interpretor if it's not caught by the client code.
'''              
               
          
          
          
         
  

    
          
 
