nr=int(input('Enter number of resistors in the first loop'))
nr1=int(input('Enter number of resistors in the second loop'))
l=180
import turtle
t=turtle
t.color('red')
for i in range(0,nr):
  t.forward(100)
  t.left(45)
  t.forward(10)
  t.right(90)
  t.forward(10)
  t.left(90)
  t.forward(10)
  t.right(90)
  t.forward(10)
  t.left(90)
  t.forward(10)
  t.right(90)
  t.forward(10)
  t.left(90)
  t.forward(10)
  t.right(90)
  t.forward(10)
  t.left(45)
  t.forward(25)
  t.penup()
  t.right(90)
  t.forward(25)
  t.right(90)
  t.forward(l)
  t.right(180)
  t.pendown()
  l=l+1
t.left(90)
t.penup()
t.forward(25)
t.pendown()
for i in range(1,nr):
    t.forward(25)
t.right(90)
t.penup()
t.forward(180)
t.right(90)
t.pendown()
for i in range(1,nr):
    t.forward(25)
t.right(180)
t.forward((25*int(nr-1))/2)
t.right(90)
t.forward(30)
t.penup()
t.left(90)
t.forward((25*int(nr1-1))/2)
t.right(90)
t.pendown()
k=0
for i in range(0,nr1):
  t.forward(100)
  t.left(45)
  t.forward(10)
  t.right(90)
  t.forward(10)
  t.left(90)
  t.forward(10)
  t.right(90)
  t.forward(10)
  t.left(90)
  t.forward(10)
  t.right(90)
  t.forward(10)
  t.left(90)
  t.forward(10)
  t.right(90)
  t.forward(10)
  t.left(45)
  t.forward(25)
  t.penup()
  t.right(90)
  t.forward(25)
  t.right(90)
  t.forward(180)
  t.right(180)
  t.pendown()  
t.left(90)
t.penup()
t.forward(25)
for i in range(1,nr1):
    t.pendown()
    t.forward(25)
t.penup()
t.right(90)
t.forward(180)
t.right(90)
for i in range(0,nr1):
    t.pendown()
    t.forward(25)    
t.right(90)
t.forward(180)
t.right(90)
t.forward(10)
t.right(180)
t.forward(20)
t.right(180)
t.forward(10)
t.left(90)
t.penup()
t.forward(5)
t.pendown()
t.right(90)
t.forward(20)
t.right(180)
t.forward(40)
t.right(180)
t.forward(20)
t.left(90)
t.forward(210)
t.right(90)
for i in range(0,nr):
    t.forward(25)

#z=int(input('Enter the number of branches of parallel circuits'))
#for p in range(1,z+1):
k=0
for j in range(1,nr+1):
    r1=int(input('Enter the value of the resistance'))
    k=k+1/r1
print('The value of resistance in 1st branch of parallel connection is',1/k)
n=0
for k in range(1,nr1+1):
    r2=int(input('Enter the value of resistance'))
    n=n+1/r2
print('The value of resistance in the 2nd branch of parallel connection is',1/n)
print('The equivalent resistance of the circuit is',n+k)            
    


    


