l=180
a=int(input("Enter number of resistors in series:"))
r=int(input('Confirm the  number of resistors in series'))
nr=int(input('Enter no of resistors in parallel:'))
s=int(input('Confirm the number of resisitors in parallel'))
import turtle
t=turtle.Turtle()
t.color('red')
for i in range(a):
  t.forward(50)
  t.left(45)
  t.forward(10)
  t.right(90)
  t.forward(10)
  t.left(90)
  t.forward(10)
  t.right(90)
  t.forward(10)
  t.left(90)
  t.forward(10)
  t.right(90)
  t.forward(10)
  t.left(90)
  t.forward(10)
  t.right(90)
  t.forward(10)
  t.left(45)
  t.forward(50)
for i in range(0,nr):
  t.forward(100)
  t.left(45)
  t.forward(10)
  t.right(90)
  t.forward(10)
  t.left(90)
  t.forward(10)
  t.right(90)
  t.forward(10)
  t.left(90)
  t.forward(10)
  t.right(90)
  t.forward(10)
  t.left(90)
  t.forward(10)
  t.right(90)
  t.forward(10)
  t.left(45)
  t.forward(25)
  t.penup()
  t.right(90)
  t.forward(25)
  t.right(90)
  t.forward(l)
  t.right(180)
  t.pendown()
  l=l+1
t.penup()
t.left(90)
t.forward(25)
t.pendown()
for i in range(nr-1):
  t.forward(25)
t.penup()
t.right(90)
t.forward(180)
t.right(90)
t.pendown()
for i in range(nr-1):
  t.forward(25)
t.right(180)
for i in range(1):
  t.forward((25*int(nr-1))/2)
t.right(90)
t.forward(10)
t.right(90)
t.forward(100)
t.right(90)
t.forward(135+180*int(a))
t.right(180)
t.circle(50)
t.penup()
t.left(90)
t.forward(10)
t.right(90)
t.pendown()
t.left(120)
t.forward(60)
t.right(180)
t.forward(60)
t.left(120)
t.forward(60)
t.right(180)
t.forward(60)
t.left(45)
t.penup()
t.forward(10)
t.pendown()
t.right(15)
t.right(90)
t.forward(70)
t.right(90)
t.forward(100+(25/2)*int((nr-1)))
t.right(90)
t.goto(0,0)
l=0
for i in range(1,r+1):
    q=int(input('Enter the value of the resistor'))
    l+=q
v=print('The series equivalent resistance is',l)
k=0
for j in range(1,s+1):
    r2=int(input('Enter the value of the resistance'))
    k=k+1/r2
w=print('The parallel equivalent resistance is',1/k)
print('The equivalent resistance of the chosen circuit is',l+1/k)

s
